import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { findAttribution, isAiIdentity } from '../../src/core/attribution.mjs';

const cli = path.resolve('src/cli.mjs');

function repo({ name = 'Human Dev', email = 'dev@example.com' } = {}) {
  const root = mkdtempSync(path.join(tmpdir(), 'engineering-os-attribution-'));
  execFileSync('git', ['init', '-q', root]);
  execFileSync('git', ['-C', root, 'config', 'user.name', name]);
  execFileSync('git', ['-C', root, 'config', 'user.email', email]);
  return root;
}

function commit(root, message, env = {}) {
  writeFileSync(path.join(root, `f-${Math.random().toString(36).slice(2)}.txt`), 'x');
  execFileSync('git', ['-C', root, 'add', '-A']);
  return spawnSync('git', ['-C', root, 'commit', '-q', '-F', '-'], { input: message, encoding: 'utf8', env: { ...process.env, ...env } });
}

function runHook(root, event) {
  return spawnSync(process.execPath, [path.join(root, '.engineering-os', 'hooks', 'no-ai-attribution.mjs')], {
    input: JSON.stringify(event), encoding: 'utf8', env: { ...process.env, CLAUDE_PROJECT_DIR: root }
  });
}

test('patterns catch AI attribution but not product names or human co-authors', () => {
  for (const text of [
    'Fix\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>',
    'Co-authored-by: GitHub Copilot <copilot@example.com>',
    '\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)',
    'Claude-Session: https://claude.ai/code/session_123',
    'Generated by ChatGPT'
  ]) assert.ok(findAttribution(text).length > 0, text);
  for (const text of [
    'Wire the Claude Code hooks into .claude/settings.json',
    'Co-authored-by: Jane Doe <jane@example.com>',
    'Merge pull request #1 from team/feature',
    'Retain maintainer detail'
  ]) assert.deepEqual(findAttribution(text), [], text);
  assert.equal(isAiIdentity('Claude <noreply@anthropic.com>'), true);
  assert.equal(isAiIdentity('Maida Chen <maida@example.com>'), false);
});

test('init-project turns Claude Code attribution off and wires the attribution hook', () => {
  const root = repo();
  execFileSync(process.execPath, [cli, 'init-project', '--target', root]);
  const settings = JSON.parse(readFileSync(path.join(root, '.claude', 'settings.json'), 'utf8'));
  assert.deepEqual(settings.attribution, { commit: false, pr: false, sessionUrl: false });
  assert.match(readFileSync(path.join(root, 'CLAUDE.md'), 'utf8'), /No AI attribution anywhere in Git or on GitHub/);
  assert.match(readFileSync(path.join(root, 'AGENTS.md'), 'utf8'), /No AI attribution in Git or on GitHub/);
});

test('the PreToolUse hook blocks attributed git/gh commands and GitHub tool calls only', () => {
  const root = repo();
  execFileSync(process.execPath, [cli, 'init-project', '--target', root]);
  const blocked = runHook(root, { tool_name: 'Bash', tool_input: { command: 'git commit -m "Fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"' } });
  assert.equal(blocked.status, 2);
  assert.match(blocked.stderr, /AI co-author trailer/);
  assert.equal(runHook(root, { tool_name: 'Bash', tool_input: { command: 'gh pr create --title x --body "Generated with Claude Code"' } }).status, 2);
  assert.equal(runHook(root, { tool_name: 'mcp__github__create_pull_request', tool_input: { title: 't', body: 'x\n\nhttps://claude.ai/code/session_1' } }).status, 2);

  assert.equal(runHook(root, { tool_name: 'Bash', tool_input: { command: 'git commit -m "Wire Claude Code hooks"' } }).status, 0);
  assert.equal(runHook(root, { tool_name: 'Bash', tool_input: { command: 'grep -rn "Co-Authored-By: Claude" .' } }).status, 0);
  assert.equal(runHook(root, { tool_name: 'Read', tool_input: { file_path: 'x' } }).status, 0);
});

test('the git commit-msg hook rejects AI trailers and AI identities, and allows clean commits', () => {
  const root = repo();
  execFileSync(process.execPath, [cli, 'init-project', '--target', root]);
  assert.equal(commit(root, 'Initial import').status, 0);

  const trailer = commit(root, 'Add feature\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n');
  assert.notEqual(trailer.status, 0);
  assert.match(trailer.stderr, /AI co-author trailer/);

  const identity = commit(root, 'Clean message', { GIT_AUTHOR_NAME: 'Claude', GIT_AUTHOR_EMAIL: 'noreply@anthropic.com' });
  assert.notEqual(identity.status, 0);
  assert.match(identity.stderr, /author is an AI identity/);

  assert.equal(commit(root, 'Add feature\n\nCo-authored-by: Jane Doe <jane@example.com>\n').status, 0);
  assert.equal(JSON.parse(execFileSync(process.execPath, [cli, 'check-attribution', '--target', root], { encoding: 'utf8' })).clean, true);
});

test('the commit-msg hook never replaces an existing hook or a core.hooksPath setup', () => {
  const existing = repo();
  mkdirSync(path.join(existing, '.git', 'hooks'), { recursive: true });
  writeFileSync(path.join(existing, '.git', 'hooks', 'commit-msg'), '#!/bin/sh\nexit 0\n');
  const result = JSON.parse(execFileSync(process.execPath, [cli, 'init-project', '--target', existing], { encoding: 'utf8' }));
  assert.equal(result.adapter.commitMsg.status, 'skipped-existing-hook');
  assert.equal(readFileSync(path.join(existing, '.git', 'hooks', 'commit-msg'), 'utf8'), '#!/bin/sh\nexit 0\n');

  const managed = repo();
  execFileSync('git', ['-C', managed, 'config', 'core.hooksPath', '.husky']);
  const skipped = JSON.parse(execFileSync(process.execPath, [cli, 'init-project', '--target', managed], { encoding: 'utf8' }));
  assert.equal(skipped.adapter.commitMsg.status, 'skipped-core-hooksPath');
  assert.equal(existsSync(path.join(managed, '.git', 'hooks', 'commit-msg')), false);
});

test('check-attribution finds attributed commits, AI identities and PR text', () => {
  const root = repo();
  assert.equal(commit(root, 'Clean start').status, 0);
  const base = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  assert.equal(commit(root, 'Add\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n', { GIT_COMMITTER_NAME: 'Claude', GIT_COMMITTER_EMAIL: 'noreply@anthropic.com' }).status, 0);

  const result = spawnSync(process.execPath, [cli, 'check-attribution', '--target', root, '--range', `${base}..HEAD`, '--text', 'Generated with Claude Code'], { encoding: 'utf8' });
  assert.equal(result.status, 1);
  const report = JSON.parse(result.stdout);
  assert.equal(report.commitsChecked, 1);
  assert.deepEqual([...new Set(report.findings.map((item) => item.field))].sort(), ['committer', 'message', 'text']);
  assert.equal(JSON.parse(execFileSync(process.execPath, [cli, 'check-attribution', '--target', root, '--range', base], { encoding: 'utf8' })).clean, true);
});

test('upgrade adds the attribution hook and setting to a project installed by an older kit', () => {
  const root = repo();
  execFileSync(process.execPath, [cli, 'init-project', '--target', root]);
  const settingsPath = path.join(root, '.claude', 'settings.json');
  const old = JSON.parse(readFileSync(settingsPath, 'utf8'));
  old.hooks.PreToolUse = old.hooks.PreToolUse.filter((entry) => entry.matcher !== 'Bash|mcp__.*');
  delete old.attribution;
  writeFileSync(settingsPath, JSON.stringify(old));
  execFileSync(process.execPath, [cli, 'upgrade', '--target', root]);
  const upgraded = JSON.parse(readFileSync(settingsPath, 'utf8'));
  assert.equal(upgraded.hooks.PreToolUse.length, 2);
  assert.deepEqual(upgraded.attribution, { commit: false, pr: false, sessionUrl: false });
});

test('doctor fails on an AI git identity and warns about attributed history', () => {
  const root = repo({ name: 'Claude', email: 'noreply@anthropic.com' });
  execFileSync(process.execPath, [cli, 'init-project', '--target', root]);
  const report = JSON.parse(spawnSync(process.execPath, [cli, 'doctor', '--target', root], {
    encoding: 'utf8', env: { ...process.env, CLAUDE_CONFIG_DIR: mkdtempSync(path.join(tmpdir(), 'engineering-os-attr-home-')) }
  }).stdout);
  const identity = report.checks.find((item) => item.name === 'git-identity');
  assert.equal(identity.status, 'fail');
  assert.match(identity.fix, /git config user.name/);
});
